apiVersion: v1
kind: Service
metadata:
  name: kubecenter-api
  namespace: default
  labels:
    app: kubecenter-api
spec:
  type: ClusterIP
  selector:
    app: kubecenter-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
