apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecenter
  namespace: kubecenter
  labels:
    app.kubernetes.io/part-of: kubecenter
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: kubecenter.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubecenter-front
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kubecenter-api
                port:
                  number: 8080
