apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubecenter
  namespace: kubecenter
  labels:
    app.kubernetes.io/part-of: kubecenter
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`kubecenter.example.com`)
      kind: Rule
      services:
        - name: kubecenter-front
          port: 3000
